Jacoco 설정, Redis 적용 (Refresh token) 및 카카오 로그인 구현
dnd-side-project/dnd-8th-2-backend pull request #20
Opened 2023-02-20 05:59 UTC by HunSeongPark

## 🔥 Related Issue
- Close #11 

## 🏃‍ Task
- Jacoco 의존성 추가 및 설정 (Test Coverage 70%, 테스트 범위 Controller, Service로 설정)
- Redis / Embedded-Redis (for test) 의존성 추가
- JWT 의존성 추가
- 카카오 api 호출을 위한 Http Client 의존성 추가
- 카카오 로그인 구현
- access token을 검증하는 인증 필터 구현
- refresh 로직 구현
- Redis 관련 테스트 코드 작성

## 📄 Reference
- Spring + Redis 세팅 : https://hudi.blog/refresh-token-in-spring-boot-with-redis
- ElastiCache : https://devlog-wjdrbs96.tistory.com/314
- Embedded Redis를 사용한 Test : https://jojoldu.tistory.com/297
- 

## ✅ Check List
- [ ]  PR의 제목은 팀 내 규칙을 준수하여 알맞게 작성하였는가?
- [ ]  Merge 하는 브랜치가 올바른가? (`main` branch에 실수로 PR 생성 금지)
- [ ]  팀의 코딩 컨벤션을 준수하는가?
- [ ]  PR과 관련없는 변경사항이 들어가지는 않았는가?
- [ ]  내 코드에 대한 자기 검토가 되었는가?
- [ ]  Reviewers, Assignees, Lables, Project, Milestone은 적절하게 선택하였는가?
- [ ]  관련한 issue를 닫아야 하는지 점검해보고 적용했는가?

2023-02-20 08:26 UTC, HunSeongPark commented
@Wo-ogie 코드 충돌 해결해서 push 해놨습니다!

2023-02-20 10:58 UTC, Wo-ogie requested changes
Request, Response는 내부에 따로 package 생성하여 구조화해주시면 좋을 것 같습니다.

2023-02-20 10:58 UTC, Wo-ogie commented on src/main/java/com/dnd/reetplace/app/config/SecurityConfig.java
>              // TODO: 추후 로그인 권한이 필요하지 않은 API의 uri 기입
아무것도 없어서 써놓았던건데 이제 TODO 지워주셔도 될 것 같습니다!

2023-02-20 10:58 UTC, Wo-ogie commented on src/main/java/com/dnd/reetplace/app/type/RoleType.java
> +    GUEST("ROLE_GUEST", "게스트 사용자");
저희 유저 권한 하나만 유지해도 되지 않을까요?
아니면 차라리 admin 권한을 추가하는게 나을 것 같습니다. (추후 백오피스 서비스 개발 고려)

2023-02-20 10:58 UTC, Wo-ogie commented on src/main/java/com/dnd/reetplace/global/exception/ExceptionType.java
> +    JWT_UNSUPPORTED_EXCEPTION(1103, "처리할 수 없는 token입니다.", UnsupportedJwtException.class),
"15XX: 인증 관련 예외"로 따로 빼도 괜찮을 거 같아요! 인증 관련 예외는 앞으로도 더 생길 것 같으니까요.

2023-02-20 10:58 UTC, Wo-ogie commented on src/main/java/com/dnd/reetplace/global/exception/ExceptionType.java
> +     */
여기 custom exception쪽 전체적으로 코드 formatting이 안맞는 거 같아요! `,MemberUidNotFoundException .class` 이렇게 되어있는데 코드 정리 한 번 해주시면 좋을 것 같습니당

2023-02-20 10:58 UTC, Wo-ogie commented on src/main/java/com/dnd/reetplace/global/security/JwtAccessDeniedHandler.java
> +     */
code, message로 주석 변경해주세요! #21 에서 error response 형태가 변경되어서요.

2023-02-20 10:58 UTC, Wo-ogie commented on src/main/java/com/dnd/reetplace/app/controller/AuthController.java
> +    public ResponseEntity<LoginResponse> kakaoLogin(HttpServletRequest request) throws JsonProcessingException {
Controller layer에서 checked exception을 그대로 던지는건 예측하지 못한 에러가 발생할 수 있다는 문제가 있을 것 같아요.
가능하다면 처음 해당 예외가 던져질 가능성이 있는 곳에서, 그게 어렵다면 service layer에서라도 예외를 복구하면 좋을 것 같습니다.

2023-02-20 10:58 UTC, Wo-ogie commented on src/main/java/com/dnd/reetplace/app/controller/AuthController.java
> +    @GetMapping("/login/kakao")
"멱등성이 보장되는가?"를 생각해보았을 때 이 API는 멱등성이 보장된다고 하기 어려울 것 같아요.
회원가입을 진행하는 로직도 존재하고, 요청할때마다 다른 응답이 넘어올 뿐만 아니라 refresh token도 저장하고 있는 거 같아서요.
때문에 `POST`로 변경해야 할 것 같습니다.

2023-02-20 10:58 UTC, Wo-ogie commented on src/main/java/com/dnd/reetplace/app/service/OAuth2Service.java
> +
현재 이 method에는 너무 많은 책임이 들어있는 것 같아요.
Kakao server와 HTTP connection을 연결하여 통신해야 하고, 로그인도 해야하고, 필요한 경우 회원가입도 진행해야 하는데요. 가능하면 이 method에 부여된 큰 세 가지 책임을 분산시켰으면 좋겠습니다.
1. 외부 서버와 HTTP communication을 하는 역할은 별도의 class로 구분하여 추후 필요하다면 다른 곳에서 재사용 할 수 있도록 분리하면 어떨까 싶습니다.
2. 회원가입 로직은 별도의 method로 extract하여 코드 가독성은 높이고 각 method의 핵심 책임을 분산시켰으면 좋겠습니다.
3. login method는 이제 login을 해야 하는 책임만 짊어지고 kakao server와의 communication과 회원가입은 위에서 구현한 기능에게 책임을 위임하여 로직이 수행되면 좋을 것 같습니다.

2023-02-20 10:58 UTC, Wo-ogie commented on src/main/java/com/dnd/reetplace/app/service/OAuth2Service.java
> +        String token = tokenProvider.getToken(request);
Kakao access token와 저희 서비스의 access token이 같은 곳에 담겨서 오는 것 같습니다. 맞을까요?
혹시 성격이 다른 두 token이 같은 곳에 담겨서 와도 괜찮을지 여쭤보고 싶습니다.

2023-02-20 10:58 UTC, Wo-ogie commented on src/main/java/com/dnd/reetplace/app/service/OAuth2Service.java
> +            log.error("OAuth2Service.kakaoLogin() ex={}", String.valueOf(e));
로그를 출력할 때 어떤 요청에 대한 로그인지를 명시하는게 좋을 것 같습니다.
다음과 같이 한다면 각 요청에 대해 고유하게 생성된 log trace id를 함께 출력할 수 있습니다.
```suggestion
            log.error("[{}] OAuth2Service.kakaoLogin() ex={}", LogUtils.getLogTraceId(), String.valueOf(e));
```

사실 가능하다면 모든 로그 출력에 해당 prefix를 자동으로 넣고 싶은데... 시간이 없어서(귀찮아서..😅) 아직 가능한 방법인지 확인을 못해봤네요.

2023-02-20 10:58 UTC, Wo-ogie commented on src/main/java/com/dnd/reetplace/app/dto/auth/LoginResponse.java
> +            Member member,
혹시 모를 문제 발생을 미연에 방지하고자, 안전하게 `MemberDto`를 받는 건 어떨까요?

2023-02-20 10:58 UTC, Wo-ogie commented on src/main/java/com/dnd/reetplace/app/service/OAuth2Service.java
> +        if (member == null) {
무언가를 DB에서 find 했는데 없을 경우, null과 같은 값을 넣는건 예측하지 못한 문제가 쉽게 발생할 수 있을 것 같아요. 때문에 `Optional` type에 대해 `orElse()`를 했을 때 null을 그대로 넣어주는 것과 비어있음을 확인하지 않고 `get()`을 사용하는 코드들은 최대한 지양했으면 좋겠습니다.

이 경우 `memberRepository.existsByUidAndLoginType(uid, LoginType.KAKAO)`로 존재 여부를 먼저 확인한 뒤 필요 로직을 수행하는 것이 좋을 것 같습니다.

2023-02-20 10:58 UTC, Wo-ogie commented on src/main/java/com/dnd/reetplace/app/service/OAuth2Service.java
> +            String email = (String) kakaoProfile.getKakao_account().get("email");
`KakaoProfile`에 `getEmail()`이라는 `public` method를 만들어두고, 외부에서는 간단하게 `kakaoProfile.getEmail()` 정도만 사용하면 어떨까요?
이렇게 하면 외부에서는 해당 객체의 구조를 몰라도 되고 객체지향의 추상화와 캡슐화가 지켜질 수 있을 것 같습니다.

2023-02-20 10:58 UTC, Wo-ogie commented on src/main/java/com/dnd/reetplace/app/service/OAuth2Service.java
> +            String email = (String) kakaoProfile.getKakao_account().get("email");
아래의 `.nickname((String) profile.get("nickname"))`도 동일한 내용이 될 것 같습니다.

2023-02-20 10:58 UTC, Wo-ogie commented on src/main/java/com/dnd/reetplace/app/service/RefreshTokenRedisService.java
> +                .orElseThrow(() -> new RefreshTokenNotFoundException(refreshToken));
Parameter로 넘어온 `refreshToken`을 log에 찍어야 할 필요가 있는지? 고민 필요

2023-02-20 10:58 UTC, Wo-ogie commented on src/test/java/com/dnd/reetplace/unit/place/AddressTest.java
> +package com.dnd.reetplace.unit.place;
`integration`, `unit` package 내에서도 package 구조가 드러났으면 좋겠습니다.
이 경우 `unit` =>  `unit.app.domain`이 되었으면 좋겠어요.

2023-02-20 10:58 UTC, Wo-ogie commented on src/main/java/com/dnd/reetplace/app/service/RefreshTokenRedisService.java
> +                .orElseThrow(() -> new RefreshTokenNotFoundException(refreshToken));
`.orElseThrow(RefreshTokenNotFoundException::new)`

2023-02-20 10:58 UTC, Wo-ogie commented on src/main/java/com/dnd/reetplace/global/security/JwtAuthenticationFilter.java
> +        boolean isLoginPath = antPathMatcher.match("/api/auth/login/**", request.getServletPath());
Access token이 날아오는 header custom 후 삭제

2023-02-20 11:01 UTC, HunSeongPark commented on build.gradle
> +jacoco {
Jacoco 테스트 커버리지 Report 확인 과정은 다음과 같습니다.
1. Gradle - verification - test 수행 (모든 test 코드 수행 및 Report 생성)
2. build/reports/jacoco/index.html 에서 Report 확인 (Open browser 등 활용)

2023-02-20 11:08 UTC, Wo-ogie commented on build.gradle
> +jacoco {
확인했습니다! 추후에 잘 막히면 다시 여쭤볼게요.

2023-02-20 17:53 UTC, Wo-ogie requested changes

2023-02-20 17:53 UTC, Wo-ogie commented on src/main/java/com/dnd/reetplace/global/security/TokenProvider.java
> +            log.error("TokenProvider.validateToken() ex={}", String.valueOf(e));
여기 로그 찍을 때 log trace id도 같이 찍어야 할 거 같아요.

2023-02-21 09:27 UTC, Wo-ogie approved these changes

2023-02-21 09:48 UTC, merged