로그인한 사용자 정보 조회 기능 구현
dnd-side-project/dnd-8th-2-backend pull request #25
Opened 2023-02-22 09:01 UTC by HunSeongPark

## 🔥 Related Issue
- Close #24 

## 🏃‍ Task
- 로그인한 사용자 정보 조회 엔드포인트 추가
- 사용자 정보 조회 로직 구현
<img width="350" alt="스크린샷 2023-02-22 오후 4 58 29" src="https://user-images.githubusercontent.com/71416677/220571781-fa552eaa-828f-4cb6-8874-9628282409c2.png">

- 테스트 코드 작성
<img width="398" alt="스크린샷 2023-02-22 오후 5 49 02" src="https://user-images.githubusercontent.com/71416677/220571808-4e07fe95-980b-430b-bca1-01d7c9930f1d.png">

- Swagger 문서 작성
<img width="412" alt="스크린샷 2023-02-22 오후 5 53 35" src="https://user-images.githubusercontent.com/71416677/220571848-55bfef9b-314c-4427-aa0f-ea92715c7794.png">

## 📄 Reference
- None

## ✅ Check List
- [ ]  PR의 제목은 팀 내 규칙을 준수하여 알맞게 작성하였는가?
- [ ]  Merge 하는 브랜치가 올바른가? (`main` branch에 실수로 PR 생성 금지)
- [ ]  팀의 코딩 컨벤션을 준수하는가?
- [ ]  PR과 관련없는 변경사항이 들어가지는 않았는가?
- [ ]  내 코드에 대한 자기 검토가 되었는가?
- [ ]  Reviewers, Assignees, Lables, Project, Milestone은 적절하게 선택하였는가?
- [ ]  관련한 issue를 닫아야 하는지 점검해보고 적용했는가?

2023-02-22 09:05 UTC, HunSeongPark commented on src/main/java/com/dnd/reetplace/app/domain/Member.java
> +        this.id = id;
@Wo-ogie 
Member 관련 테스트 코드 작성 시 id 값을 설정하지 못하게 됨으로써 테스트가 불가능 한 문제가 발생하여 
우선 Builder에서 id 필드를 열어두었습니다.

괜찮으시면 Approve 해주시고, 더 좋은 방식이 있으시면 해당 부분에 대한 의견 부탁드립니다! :)

2023-02-22 09:54 UTC, Wo-ogie commented on src/main/java/com/dnd/reetplace/app/domain/Member.java
> +        this.id = id;
Application 코드는 프로젝트 기준으로 유지하는게 맞는 거 같습니다. 즉, constructor나 fields는 접근 범위를 가능한 한 좁게 설정했으면 좋겠어요.
다만, test 할 때는 문제가 될 수 있는데 이를 위한 기술이 존재합니다. `ReflectionTestUtils`라는 기술인데 내용은 다음과 같습니다.
- JPA와 Hibernate 같은 ORM 기술을 사용할 때 setter method를 사용하지 않고 `private` or `protected` filed access를 하려는 경우 사용한다. 테스트 할 때 non-public 필드를 설정하거나, non-public constructor method를 호출하거나, non-public setter method를 호출하거나, non-public configuration or lifecycle callback method를 호출할 때 유용하다.
- 문서: https://docs.spring.io/spring-framework/docs/current/javadoc-api/org/springframework/test/util/ReflectionTestUtils.html
이 외에도 reflection 관련 기술들이 더 존재하는 걸로 아는데, `ReflectionTestUtils`의 기능이 부족하다고 생각이 되시면 더 찾아보셔도 좋을 것 같아요. 저는 일단 `ReflectionTestUtils` 정도만 써봤습니다.

2023-02-24 00:58 UTC, Wo-ogie commented on src/main/java/com/dnd/reetplace/app/dto/member/response/MemberResponse.java
> +    private String nickname;
`@Schema(description="", example="")`로 API 명세를 좀 더 자세하게 적어주시면 좋을 것 같습니다!

2023-02-24 00:58 UTC, Wo-ogie commented on src/main/java/com/dnd/reetplace/global/exception/ExceptionType.java
> +    MEMBER_ID_NOT_FOUND(2000, "ID에 해당하는 사용자를 찾을 수 없습니다.", MemberIdNotFoundException.class),
`MEMBER_UID_NOT_FOUND`와 에러 코드가 동일한데 의도하신 사항일까요?

2023-02-24 04:07 UTC, HunSeongPark commented on src/main/java/com/dnd/reetplace/global/exception/ExceptionType.java
> +    MEMBER_ID_NOT_FOUND(2000, "ID에 해당하는 사용자를 찾을 수 없습니다.", MemberIdNotFoundException.class),
앗 복사하고 에러 코드를 안 바꿨네요 수정하겠습니다 ~! 🥺

2023-02-24 07:42 UTC, Wo-ogie requested changes

2023-02-24 07:42 UTC, Wo-ogie commented on src/main/java/com/dnd/reetplace/app/controller/MemberController.java
> +    ) {
이것도 로그인 권한이 필요한 API이므로 Swagger-ui의 security 설정 적용해주세요!
```suggestion
    @Operation(
            summary = "로그인한 사용자 정보 조회", 
            description = "로그인한 사용자의 정보를 조회합니다.",
            security = @SecurityRequirement(name = "Authorization")
    )
    @GetMapping("/my")
    public ResponseEntity<MemberResponse> getLoginMemberInfo(
            @Parameter(hidden = true) @AuthenticationPrincipal MemberDetails memberDetails
    ) {
```

2023-02-24 07:53 UTC, HunSeongPark commented on src/main/java/com/dnd/reetplace/app/controller/MemberController.java
> +    ) {
PR이 섞이다보니 헷갈려서 또 빼먹었네요 죄송합니다,,🥺
수정해놨습니다!

2023-02-25 04:31 UTC, Wo-ogie approved these changes

2023-02-25 08:05 UTC, merged